name: Publish To Docker Hub

on:
  push:
  workflow_dispatch:

env:
  VERSION: "${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER"

jobs:
  server_build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd grafeo-server
          mvn --batch-mode --update-snapshots verify

  web_build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd grafeo-web
          yarn install
      - name: Generate build
        run: |
          cd grafeo-web
          yarn run build

  server_docker_publish:
    name: Server Docker Publish
    needs: [ server_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Spring Build Image
        run: |
          echo ${VERSION}
          cd grafeo-server
          mvn spring-boot:build-image
      - name: Check Docker image
        run: docker image ls
      - name: Tag Server image
        env:
          VERSION: ${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
        run: docker tag grafeo-server:0.6.0 valaz/grafeo-server:${VERSION}
      - name: Check Docker image
        run: docker image ls
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: valaz/grafeo-server
      - name: Build and push Docker image
        env:
          VERSION: ${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: valaz/grafeo-server:${VERSION}

  web_docker_publish:
    name: Web Docker Publish
    needs: [ web_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Create Docker Web Image
        run: |
          cd grafeo-web
          docker build . -t grafeo-web:latest
      - name: Check Docker image
        run: docker image ls
      - name: Tag Web image
        env:
          VERSION: ${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
        run: docker tag grafeo-web:latest valaz/grafeo-web:${VERSION}
      - name: Check Docker image
        run: docker image ls