name: Build and Deploy To Docker Hub

on:
  push:
  workflow_dispatch:

jobs:
  server_build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd grafeo-server
          mvn --batch-mode --update-snapshots verify
  web_build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd grafeo-web
          yarn install
      - name: Generate build
        run: |
          cd grafeo-web
          yarn run build
  server_dockerize:
    name: Server Dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Spring Build Image
        run: |
          ls -l
          cd grafeo-server
          mvn spring-boot:build-image
      - name: Check Docker image
        run: docker image ls
      - name: Tag AWS image
        run: docker tag grafeo-server:0.6.0 valaz/grafeo-server:${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
      - name: Check Docker image
        run: docker image ls
