name: Publish To Docker Hub

on:
  push:
  workflow_dispatch:

env:
  VERSION: "${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER"

jobs:
  server_build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd grafeo-server
          mvn --batch-mode --update-snapshots verify

  web_build:
    name: Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: |
          cd grafeo-web
          yarn install
      - name: Generate build
        run: |
          cd grafeo-web
          yarn run build

  server_docker_publish:
    name: Server Docker Publish
    needs: [ server_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          cd grafeo-server
          mvn package -DskipTests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: valaz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./grafeo-server
          push: true
          tags: valaz/grafeo-server:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BRANCH=${{ env.BRANCH }}

  web_docker_publish:
    name: Web Docker Publish
    needs: [ web_build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Get Version
        run: echo "VERSION=${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: valaz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./grafeo-web
          push: true
          tags: valaz/grafeo-web:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            BRANCH=${{ env.BRANCH }}